// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

package internal

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
)

// EnsureInstrumentationImports ensures that the required imports for instrumentation are added to the target project
func EnsureInstrumentationImports(targetDir string) error {
	// Create the importer file that imports necessary packages
	importerPath := filepath.Join(targetDir, "otel_importer.go")
	importerContent := `// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// This file was automatically generated by OpenTelemetry Go Compile Instrumentation
package main

import (
	// Import the SDK for compile-time instrumentation
	_ "github.com/open-telemetry/opentelemetry-go-compile-instrumentation/sdk"
	
	// Import AWS SDK instrumentation
	_ "go.opentelemetry.io/contrib/instrumentation/github.com/aws/aws-sdk-go-v2/otelaws"
	
	// Import common AWS service instrumentation packages when needed
	// These will be unused unless you actually create clients for these services
	_ "github.com/aws/aws-sdk-go-v2/service/dynamodb"
	_ "github.com/aws/aws-sdk-go-v2/service/s3"
	_ "github.com/aws/aws-sdk-go-v2/service/sqs"
)
`
	err := os.WriteFile(importerPath, []byte(importerContent), 0644)
	if err != nil {
		return fmt.Errorf("failed to create importer file: %w", err)
	}

	// Run go mod tidy to ensure dependencies are downloaded
	cmd := exec.Command("go", "mod", "tidy")
	cmd.Dir = targetDir
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("failed to run go mod tidy: %w", err)
	}

	return nil
}
